# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Code tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Python setup ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Dependencies installation
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pylint
        pip install -r requirements.txt
    - name: Code check with flake8
      run: |
        # exit-zero treats all errors as warnings
        flake8 src tests --select=F,E,W,R,C --count --max-complexity=10 --show-source --statistics
        # check all docstrings
        pylint src tests --disable=E0401,R0902,R0912,R0903,R0914,R0913,R0915,W0703,R0904,R1702,R0911,W0603,C0103
    - name: Tests with Pytest
      run: |
        python -m pytest tests
